name: Pyinstaller MacOS

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package Application
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          spec: "./StudyDrive Scraper.spec"
          requirements: "./requirements.txt"
          python_ver: 3.13
      - uses: actions/upload-artifact@v4
        with:
          name: "StudySnatcher - MacOS"
          path: "./dist/StudySnatcher"

  release:
    if: ${{ github.event_name == 'release' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package Application
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          spec: "./StudyDrive Scraper.spec"
          requirements: "./requirements.txt"
          python_ver: 3.13
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: "./dist/StudySnatcher"
          asset_name: "StudySnatcherMacOS"
          asset_content_type: "application/octet-stream"
